import type { AdminUser, CreditCard, Debt, Goal, IncomeSource, Lead, ObligationEntry, Offer, UserProfile } from "./types";

export const isDemoMode = process.env.NEXT_PUBLIC_DEBTIQ_DEMO_MODE !== "false";

export const seedProfile: UserProfile = {
  fullName: "Aisha Mohammed",
  mobile: "+966 55 123 4567",
  email: "aisha.mohammed@example.com",
  country: "Saudi Arabia",
  city: "Riyadh",
  employer: "Premium Retail Group",
  employmentSector: "Private Sector",
  maritalStatus: "Married",
};

export const seedAdminUsers: AdminUser[] = [
  {
    id: "u1",
    ...seedProfile,
    createdAt: "2026-06-01T09:30:00.000Z",
    lastLogin: "2026-06-14T18:05:00.000Z",
    userType: "Demo",
    status: "Active",
    profileCompletion: 100,
    incomeSourceCount: 3,
    obligationCount: 6,
    creditCardCount: 2,
    goalCount: 5,
    leadCount: 1,
  },
  {
    id: "u2",
    fullName: "Mohammed Khalid",
    mobile: "+966 54 987 6543",
    email: "mohammed.khalid@example.com",
    country: "Saudi Arabia",
    city: "Jeddah",
    employer: "Logistics Co.",
    employmentSector: "Private Sector",
    maritalStatus: "Single",
    createdAt: "2026-06-04T13:15:00.000Z",
    lastLogin: "2026-06-13T11:30:00.000Z",
    userType: "Demo",
    status: "Active",
    profileCompletion: 72,
    incomeSourceCount: 1,
    obligationCount: 3,
    creditCardCount: 1,
    goalCount: 2,
    leadCount: 1,
  },
];

export const seedDebts: Debt[] = [
  {
    id: "d1",
    type: "Personal Loan",
    name: "Salary-backed loan",
    bank: "Riyadh Bank",
    remainingBalance: 145000,
    monthlyInstallment: 4200,
    interestRate: 4.2,
    endDate: "2029-06-30",
  },
  {
    id: "d2",
    type: "Credit Card",
    name: "Travel card",
    bank: "SNB",
    remainingBalance: 18500,
    monthlyInstallment: 1900,
    interestRate: 18,
    endDate: "2026-12-30",
    limit: 35000,
  },
];

export const seedIncomeSources: IncomeSource[] = [
  {
    id: "i1",
    name: "Monthly salary",
    amount: 24000,
    type: "Salary",
  },
  {
    id: "i2",
    name: "Rental apartment",
    amount: 2000,
    type: "Rent",
  },
  {
    id: "i3",
    name: "Housing allowance",
    amount: 3000,
    type: "Housing Allowance",
  },
];

export const seedObligationEntries: ObligationEntry[] = [
  {
    id: "ob1",
    name: "Personal loan installment",
    monthlyAmount: 4200,
    category: "Loan",
    dueDay: 3,
    isRecurring: true,
    frequency: "Monthly",
    dueDate: "2026-06-03",
    startDate: "2026-01-01",
    endDate: "2029-06-30",
    allocationMethod: "Count full amount only in due month",
    savedAmount: 0,
    notes: "Salary-backed loan payment.",
  },
  {
    id: "ob2",
    name: "Credit card minimum",
    monthlyAmount: 1900,
    category: "Credit Card",
    dueDay: 18,
    isRecurring: true,
    frequency: "Monthly",
    dueDate: "2026-06-18",
    startDate: "2026-01-01",
    allocationMethod: "Count full amount only in due month",
    savedAmount: 0,
    notes: "Minimum payment for travel card.",
  },
  {
    id: "ob3",
    name: "School fees",
    monthlyAmount: 25000,
    category: "Education",
    dueDay: 10,
    isRecurring: false,
    frequency: "One-Time",
    dueDate: "2026-08-10",
    startDate: "2026-06-01",
    allocationMethod: "Spread amount monthly until due date",
    savedAmount: 0,
    notes: "One-time school fee due in August; spread monthly as a sinking fund.",
  },
  {
    id: "ob4",
    name: "Domestic worker salary",
    monthlyAmount: 2200,
    category: "Domestic Worker",
    dueDay: 28,
    isRecurring: true,
    frequency: "Monthly",
    dueDate: "2026-06-28",
    startDate: "2026-01-01",
    allocationMethod: "Count full amount only in due month",
    savedAmount: 0,
    notes: "Household payroll.",
  },
  {
    id: "ob5",
    name: "Utilities and other commitments",
    monthlyAmount: 2100,
    category: "Other",
    dueDay: 22,
    isRecurring: true,
    frequency: "Monthly",
    dueDate: "2026-06-22",
    startDate: "2026-01-01",
    allocationMethod: "Count full amount only in due month",
    savedAmount: 0,
    notes: "Utilities and recurring services.",
  },
  {
    id: "ob6",
    name: "House rent",
    monthlyAmount: 50000,
    category: "Housing",
    dueDay: 1,
    isRecurring: false,
    frequency: "Annual",
    dueDate: "2027-03-01",
    startDate: "2026-06-01",
    allocationMethod: "Spread amount monthly until due date",
    savedAmount: 5000,
    notes: "Annual rent due in March; dashboard uses required monthly saving.",
  },
];

export const seedCreditCards: CreditCard[] = [
  {
    id: "cc1",
    cardName: "Travel card",
    provider: "SNB",
    creditLimit: 35000,
    currentBalance: 18500,
    minimumPaymentDue: 1900,
    statementTotalDue: 6200,
    dueDate: "2026-06-18",
    aprOrProfitRate: 18,
    notes: "Near-due card used for travel purchases.",
  },
  {
    id: "cc2",
    cardName: "Rewards card",
    provider: "Al Rajhi",
    creditLimit: 20000,
    currentBalance: 18800,
    minimumPaymentDue: 2400,
    statementTotalDue: 7800,
    dueDate: "2026-06-25",
    aprOrProfitRate: 21,
    notes: "High-risk utilization example.",
  },
];

export const seedOffers: Offer[] = [
  {
    id: "o1",
    type: "Debt Transfer",
    title: "Lower installment debt transfer",
    bankName: "Alinma Bank",
    description: "Transfer eligible salary-backed debts into a lower monthly installment plan.",
    minSalary: 15000,
    maxSalary: 60000,
    minDebt: 50000,
    maxDebt: 400000,
    expiryDate: "2026-09-30",
    contactPerson: "Noura Saleh",
    contactNumber: "+966 11 555 0198",
    active: true,
  },
  {
    id: "o2",
    type: "Refinancing",
    title: "Credit card consolidation",
    bankName: "SAB",
    description: "Consolidate revolving balances into fixed installments with clear payoff dates.",
    minSalary: 12000,
    maxSalary: 45000,
    minDebt: 10000,
    maxDebt: 120000,
    expiryDate: "2026-08-15",
    contactPerson: "Faisal Ahmed",
    contactNumber: "+966 11 555 0172",
    active: true,
  },
  {
    id: "o3",
    type: "Mortgage",
    title: "Home finance eligibility review",
    bankName: "Bank Albilad",
    description: "Pre-screen your current obligations before applying for a home finance offer.",
    minSalary: 20000,
    maxSalary: 80000,
    minDebt: 0,
    maxDebt: 250000,
    expiryDate: "2026-10-20",
    contactPerson: "Maha Ibrahim",
    contactNumber: "+966 11 555 0134",
    active: false,
  },
];

export const seedAdminLeads: Lead[] = [
  {
    id: "l1",
    userId: "u1",
    userName: seedProfile.fullName,
    mobile: seedProfile.mobile,
    email: seedProfile.email,
    offerSelected: "Lower installment debt transfer",
    timestamp: "2026-06-10T10:20:00.000Z",
    status: "New",
  },
  {
    id: "l2",
    userId: "u2",
    userName: "Mohammed Khalid",
    mobile: "+966 54 987 6543",
    email: "mohammed.khalid@example.com",
    offerSelected: "Credit card consolidation",
    timestamp: "2026-06-11T15:45:00.000Z",
    status: "Contacted",
  },
];

export const seedGoals: Goal[] = [
  {
    id: "g1",
    name: "Clear travel card",
    type: "Pay Off Credit Card",
    targetAmount: 18500,
    currentAmount: 6200,
    targetDate: "2026-12-31",
    priority: "High",
    notes: "Reduce utilization and avoid profit charges.",
    linkedCreditCardId: "cc1",
  },
  {
    id: "g2",
    name: "Pay down personal loan",
    type: "Pay Off Debt",
    targetAmount: 145000,
    currentAmount: 28000,
    targetDate: "2028-12-31",
    priority: "Medium",
    notes: "Accelerate payoff if surplus improves.",
    linkedDebtId: "d1",
  },
  {
    id: "g3",
    name: "Next car fund",
    type: "Buy Car",
    targetAmount: 90000,
    currentAmount: 12000,
    targetDate: "2027-09-30",
    priority: "Low",
    notes: "Pause if cash flow pressure rises.",
  },
  {
    id: "g4",
    name: "Emergency fund",
    type: "Emergency Fund",
    targetAmount: 60000,
    currentAmount: 18000,
    targetDate: "2027-03-31",
    priority: "High",
    notes: "Three months of core expenses.",
  },
  {
    id: "g5",
    name: "Home down payment",
    type: "Buy Home",
    targetAmount: 250000,
    currentAmount: 45000,
    targetDate: "2029-12-31",
    priority: "Medium",
    notes: "Long-term housing goal.",
  },
];
